# Default values for jaeger.
# This is a YAML-formatted file.
# Jaeger values are grouped by component. Cassandra values override subchart values

# Overrides the image tag where default is the chart appVersion.
tag: "2.8.0"

allInOne:
  enabled: true

storage:
  # allowed values (cassandra, elasticsearch, grpc-plugin, badger, memory)
  type: cassandra
  cassandra:
    host: jaeger-cassandra
    port: 9042
    # Change this value to false if you want to avoid starting the
    # -cassandra-schema Job
    schemaJobEnabled: false
    tls:
      enabled: false
      secretName: cassandra-tls-secret
    user: user
    usePassword: true
    password: password
    keyspace: jaeger_v1_test
    ## Use existing secret (ignores previous password)
    # existingSecret:
    ## Cassandra related env vars to be configured on the concerned components
    extraEnv:
      []
      # - name: CASSANDRA_SERVERS
      #   value: cassandra
      # - name: CASSANDRA_PORT
      #   value: "9042"
      # - name: CASSANDRA_KEYSPACE
      #   value: jaeger_v1_test
      # - name: CASSANDRA_TLS_ENABLED
      #   value: "false"
    ## Cassandra related cmd line opts to be configured on the concerned components
    cmdlineParams:
      {}
      # cassandra.servers: cassandra
      # cassandra.port: 9042
      # cassandra.keyspace: jaeger_v1_test
      # cassandra.tls.enabled: "false"

# Begin: Override values on the Cassandra subchart to customize for Jaeger
cassandra:
  persistence:
    # To enable persistence, please see the documentation for the Cassandra chart
    enabled: true
    # size: 100Gi
  config:
    cluster_name: jaeger
    seed_size: 1
    dc_name: dc1
    rack_name: rack1
    endpoint_snitch: GossipingPropertyFileSnitch
# End: Override values on the Cassandra subchart to customize for Jaeger

# Begin: Default values for the various components of Jaeger
# This chart has been based on the Kubernetes integration found in the following repo:
# https://github.com/jaegertracing/jaeger-kubernetes/blob/main/production/jaeger-production-template.yml
#

collector:
  enabled: true
  image:
    tag: "2.8.0"
  autoscaling:
    enabled: true
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  service:
    # can accept Zipkin spans in JSON or Thrift
    zipkin:
      port: 9411
      # nodePort:
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
        # nodePort:
      http:
        name: otlp-http
        port: 4318
        # nodePort:

# End: Default values for the various components of Jaeger

